project:
  type: book
  resources:
    - figures/**
    - BookCoverFull.png
  output-dir: _site

book:
  title: "Patterns from Static: Philosophy and the Question Concerning Statistics"
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
  cover-image: BookCoverFull.png

bibliography: PoS-Bibliography.bib
csl: csl/apa.csl

format:
  html:
    css: styles.css
    grid:
      margin-width: 350px
    reference-location: margin
    citation-location: margin
  pdf:
    pdf-engine: lualatex

crossref:
  chapters: true

filters:
  - filters/latex_to_quarto.lua
